name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once hourly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dark
          path: resources/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=dark&langs_count=20
          path: resources/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate CuscuzBane pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=CuscuzBane&theme=dark&description_lines_count=3
      #     path: resources/pin-CuscuzBane.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate PistoleiroPaco pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=PistoleiroPaco&theme=dark&description_lines_count=3
      #     path: resources/pin-PistoleiroPaco.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate trabalho-ml2023 pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=trabalho-ml2023&theme=dark&description_lines_count=3
      #     path: resources/pin-trabalho-ml2023.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate ML2023-GabrielMaiaGondim pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=ML2023-GabrielMaiaGondim&theme=dark&description_lines_count=3
      #     path: resources/pin-ML2023-GabrielMaiaGondim.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate NewHome pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=NewHome&theme=dark&description_lines_count=3
      #     path: resources/pin-NewHome.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate keybLayoutOptimizer pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=keybLayoutOptimizer&theme=dark&description_lines_count=3
      #     path: resources/pin-keybLayoutOptimizer.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate nn-image pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=nn-image&theme=dark&description_lines_count=3
      #     path: resources/pin-nn-image.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate dvst pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=dvst&theme=dark&description_lines_count=3
      #     path: resources/pin-dvst.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate pin card
      #   uses: readme-tools/github-readme-stats-action@v1
      #   with:
      #     card: pin
      #     options: username=gammag4&repo=<your-repo-here>&theme=dark
      #     path: resources/pin-readme-tools-github-readme-stats.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add resources/*.svg
          git commit -m "Update README cards" || exit 0
          git push
